### ISSUE TITLE
The button doesn't respond.

### ISSUE THREAD

**Issue by J-Z-P** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#23]
It said that "API down or unknown error".
![2020-09-08 20-27-01 的屏幕截图](https://user-images.githubusercontent.com/46836700/92476593-cadbf500-f211-11ea-8c8d-3de11ad31f8e.png)

**Comment by JoeSL** [comment]
Hello @J-Z-P  this issue has already been addressed on firefox. We recommend to use the app with google chrome or chromium.
Thank you
