### ISSUE TITLE
Support for IBM Power Architecture (ppc64le)

### ISSUE THREAD

**Issue by mgiessing** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#26]
Hello, 

is it possible to get support for IBM Power architecture (ppc64le) / crossbuilds?
The requirements should be met with existing GPU server models (S822LC, AC922 and IC922)

Thanks!

**Comment by hadikoub** [comment]
unfortunately, We are not currently working toward supporting IBM Power architecture
