### ISSUE TITLE
URL malformed on RHEL

### ISSUE THREAD

**Issue by mistaleee** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#28]
Hi!

I am trying to install the BMW Training GUI on a RHEL machine --> AC922, IBM Power architecture (ppc64le).

I reach the landing page with http://172.22.68.64:4200/training, but then I get a notification:

'The URI is malformed' in Firefox.

![URL_malformed](https://user-images.githubusercontent.com/24625384/105490551-3b614b00-5cb5-11eb-8eae-6bd0e9e3b140.jpg)

Failed to execute 'open' on 'XMLHttpRequest': Invalid URL in chromium:

![failed_to_execute_open_on_xmlhttprequest_invalid_url](https://user-images.githubusercontent.com/24625384/105490647-5cc23700-5cb5-11eb-9314-17c17beea703.jpg)

The requesting machine is in the same network and has the operating system: Ubuntu 18.04.

I installed the setup also on the requesting machine Ubuntu 18.04. and it worked (i don´t think it´s network related). I´ve been searching in the code for anything which could cause the error, but I cannot find it.

Does anyone have an idea what causes the problem or even a solution on how the problem can be solved?

I appreciate any hints. Thanks.

**Comment by JoeSL** [comment]
It seems like an issue with the URL format. It would be helpful if you could open the network tab of the browser and try to refresh the page so you could see the URL that app is trying to reach.

Another helpful thing that you could do is to provide screenshots of your environment.ts and environment.prod.ts files.

**Comment by mistaleee** [comment]
Hi Joe,

sorry for the late reply.

I took a screenshot of the environment.ts (the environment.prod.ts looks the same)

![image](https://user-images.githubusercontent.com/24625384/105735832-70c79c00-5f34-11eb-9218-bcc7a90ec7a4.png)

I also took a screenshot of the network tab:

![image](https://user-images.githubusercontent.com/24625384/105736091-b7b59180-5f34-11eb-9416-ab30df772122.png)

I installed the setup on an Ubuntu machine and if I look at the network tab, it looks like this:

![image](https://user-images.githubusercontent.com/24625384/105736198-d582f680-5f34-11eb-9796-4f40d30f577b.png)

Actually, I don´t see which URL is requested in the network tab or at least nothing which is conspicuous.

**Comment by JoeSL** [comment]
Hello,

Okay could you please try and click on any of the get_finished_jobs you see in the network tab, this will give us more information about the transaction that happened. Also could you make sure that the api is running on the specified IP? Just enter the ip you provided in your browser and make sure it is reachable.

**Comment by mistaleee** [comment]
Hello,

when I enter http://172.22.68.64:4200/training, i get to the start page

![image](https://user-images.githubusercontent.com/24625384/105814840-49171900-5fb2-11eb-9d78-3f58c3b507b5.png)

I can also ping the machine (it is in the same network). So, it´s reachable.

Unfortunately, it is not requesting the get_finished_jobs as i see in the network tab:
![image](https://user-images.githubusercontent.com/24625384/105815040-9d21fd80-5fb2-11eb-85d3-bedf44894275.png)

But when I enter it manually (http://172.22.68.64:2222/get_finished_jobs), I get an empty array back with the http message 200 OK. 

In the console tab, I see following error (browser = chromium):
![image](https://user-images.githubusercontent.com/24625384/105816987-4e299780-5fb5-11eb-9a5b-df1e76e5918b.png)


I guess there might be something wrong with the routing or building the correct URL. What do you think?

**Comment by mistaleee** [comment]
any updates on this?

**Comment by JoeSL** [comment]
It might be a browser related issue. Could you try to use regular chrome instead of chromium and trying again?

**Comment by mistaleee** [comment]
Yes, I tried. It is the same issue coming up.

**Comment by hadikoub** [comment]
@mistaleee Is this problem still relevant?
