### ISSUE TITLE
API down or unknown error

### ISSUE THREAD

**Issue by scofield1991** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#3]
I tried to run the project remotely on AWS but when tried to open the link: http://localhost:4200/training got the error: API down or unknown error. Do you know what may be the reason?

**Comment by JoeSL** [comment]
This means that the gui is not able to reach the api.
please make sure that you have the correct URL for the api in the environment.ts and environment.prod.ts files in the front-end.

**Comment by fangcywangermu** [comment]
I don't have your contact information

> 我尝试在AWS上远程运行该项目，但是当尝试打开链接时：[http：// localhost：4200 / training](http://localhost:4200/training)出现错误：API关闭或未知错误。你知道可能是什么原因吗？

hello

**Comment by fangcywangermu** [comment]
> 我尝试在AWS上远程运行该项目，但是当尝试打开链接时：[http：// localhost：4200 / training](http://localhost:4200/training)出现错误：API关闭或未知错误。你知道可能是什么原因吗？

i am a graduate from USTB ,i have some questions about your https://github.com/scofield1991/Lidar-Aided-ORBSLAM

**Comment by fangcywangermu** [comment]
> I tried to run the project remotely on AWS but when tried to open the link: http://localhost:4200/training got the error: API down or unknown error. Do you know what may be the reason?

could you tell me about your contact information,eg ,your email?

**Comment by Adrianopeniche** [comment]
Despite been sure of the ips in environment.ts and environment.prod.ts files, I'm still getting the  API down or unknown error. How can I test it better to find the problem?
