### ISSUE TITLE
Performance issues in training_api/research/object_detection/utils/ops.py

### ISSUE THREAD

**Issue by JamesCao2048** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#38]
Hello, I found that in training_api/research/object_detection/utils/ops.py,  `tf.zeros` and` tf.shape `are repeatedly created in the loop, [here](https://github.com/BMW-InnovationLab/BMW-TensorFlow-Training-GUI/blob/ecf941242e3c7380d2e6060652d209509bc9f224/training_api/research/object_detection/utils/ops.py#L705). As they ratain same in each iteration,  I think they should be moved before the loop to avoid creating redundant nodes in the tf computation graph.

Looking forward to your reply.  Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by DLPerf** [comment]
@Daniel-Jess Hello, bro, I hope you could deal with the issue asap.

**Comment by hadikoub** [comment]
@JamesCao2048  Hello, regarding you issue, the file you are mentioning is based on TF1 Object detection API without any modification [link](https://github.com/tensorflow/models/blob/57e075203f8fba8d85e6b74f17f63d0a07da233a/research/object_detection/utils/ops.py#L711)
It would be helpful if you can raise this issue to the TensorFlow git repository and then if this modification is accepted, then we can make adjustments to the current code.
