### ISSUE TITLE
Can I use this project without nvidia gpu?

### ISSUE THREAD

**Issue by hemaAI** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#4]
I have a MacBook with Ubuntu in VirtualBox but my machine does not have a Nvidia GPU is there a way to run this project?

**Comment by JoeSL** [comment]
The project specifically uses tensorflow-gpu for training. Tensorflow-gpu requires CUDA which requires an nvidia gpu. 
You can use Tensorflow without a gpu only for inference purposes
