### ISSUE TITLE
colab

### ISSUE THREAD

**Issue by localhost-server** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#57]
Is there any method to run the same thing on colab for training purpose?

**Comment by hadikoub** [comment]
For the current implementation, the deployment is done using docker and on-premise with no support for Colab. The training logic is based on TF2 object detection API and thus the training functionality can be adapted to be used on Colab with modifications.

**Comment by localhost-server** [comment]
For hackathon purpose it would be tough for those who lack with gpu architecture adding colab feature would open the whole project in new dimention I tried to run the repo on colab but after all procedure done I was unable to run "docker-compose -f run_gpu.yml up" also keeping the whole project for Ubuntu 18.04 specifically irrittates somewhat . Please add some mobility to this app for the sake of poartability.

**Comment by hadikoub** [comment]
Unfortunately, the requested feature contradicts the solution purpose as a centrally deployed GUI. Adapting the solution to run on colab will change the application identity and purpose. Our application is targeted to non-professionals in addition to pro users and making it runnable on colab will remove the GUI idea completely and changes the scope of the application. 
In case you're seeking to run the Tensorflow object detection API v2 on colab, TF2 has multiple jupyter notebooks for this reason, you can find them on: https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/index.html
