### ISSUE TITLE
Training job crash if classes are digits

### ISSUE THREAD

**Issue by torkem** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#61]
Hi !
I am working on a use case where the object to detect is a serial number engraved on a part.
To achieve that, I've annotated serial number's digits (from 0 to 9). But, when I start the training, the job crashes.
If I add any letter after the digit (1A instead of 1), the training succeeds.
Thanks for the help

**Comment by hadikoub** [comment]
Hello, 

Is it possible to share a sample annotation? are you saving the numbers as strings or numbers?
Additionally, is it possible to share the error log ?

**Comment by torkem** [comment]
[1854537_1.txt](https://github.com/BMW-InnovationLab/BMW-TensorFlow-Training-GUI/files/10343423/1854537_1.txt)
I attached the annotation file I'm using. You'll notice that I've added an A at each digits to make it working.
(I had to rename the file to txt, xml aren't supported by github)

**Comment by hadikoub** [comment]
I tried to reproduce the error based on the sample file you provided and the error is happening in the TF record generation step. 
I pushed a patch to enforce conversion to str for the class name as in your case the numbers are being cast into int and not str which is causing the error. 
commit: https://github.com/BMW-InnovationLab/BMW-TensorFlow-Training-GUI/commit/6321860221fb7677bafed4037826b8d30e5521fc
Can you please check if the newer version fixes your issue? Please make sure to include double quotes in the objectclasses.json for class names as well example:

```
[
    {
        "Id": 0,
        "Name": "1"
    },
    {
        "Id": 1,
        "Name": "2"
    }
]
```

**Comment by torkem** [comment]
Sorry for the delay, I confirm that this issue is fixed, thanks @hadikoub !
