### ISSUE TITLE
Creating job crashing between step 2 and 3

### ISSUE THREAD

**Issue by Aestyo** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#63]
Hello !

I try to start a job and after clicking next in "General Settings" it loads for 30 sec then displays "An error has occurred". I tested on Chrome and Firefox, in localhost I get the error "Cross-origin request blocked" in the browser console.
I modified the environment.ts config file to use the right domain name.
I did not find any interesting logs in the 3 containers.

Do you have any idea where the problem could come from?
Thanks in advance

**Comment by hadikoub** [comment]
Hello 

Are you able to see the response of the sent request in the network tab ?

**Comment by Aestyo** [comment]
Yes, 
"Container Name Not Found : Job Not Killed Test" 
Is that it?

**Comment by hadikoub** [comment]
yes, 
Are you using GPU or CPU version? 
I suspect that you have an issue while creating the training job container.
Can you please double-check that you installed and configured all the prerequisites correctly?
You can find all the steps that you need to configure in the Readme file https://github.com/BMW-InnovationLab/BMW-TensorFlow-Training-GUI#setting-up-project-requirements-automated
After this please rebuild the solution and let me know if this fixes your issue.

**Comment by Aestyo** [comment]
I'm using GPU version.
Docker-compose is installed, my network interface is working, i've setup the proxy and selected all the pre-trained models.
My nvidia-smi tells i got my Quadro P2200 with CUDA 12 and driver version 525.78.01

Wouldn't there be an interesting error message in the container logs if he couldn't create it? Can't find more informations than "An error has occurred"

**Comment by Aestyo** [comment]
Okay, my bad. 
There was an error in the base_dir of the paths.json !
Now it's working, thank you for your help !
