### ISSUE TITLE
Docker-Py 4.3.1 needs requests<2.2.29

### ISSUE THREAD

**Issue by Aestyo** [BMW-InnovationLab/BMW-TensorFlow-Training-GUI#64]
Hi, the new versions of requests use the distributed version of urllib3, breaking the compatibility with docker-py. 
Setting the requests version in requirements.txt to requests==2.28.1 fixes the problem.

For more information, see this issue: 
[urllib3 v2 incompatibility #3113](https://github.com/docker/docker-py/issues/3113)

**Comment by hadikoub** [comment]
@Aestyo  Thank you for the suggestion!
I checked the current requirements, and the urllib3 version inside the docker_sdk_api container is `urllib3==2.0.7`. Did you face any issues with the build and run part? if yes is it possible to attach a screenshot /log for the error? 

In all cases, I will lock the version of urllib3 to a compatible version as a safe measure.

**Comment by Aestyo** [comment]
I face the same problem as in the linked thread when I start the container, no problem with the build though.
